services:
  - type: web
    name: tnska-website
    env: node
    region: singapore # Or frankfurt / oregon / ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
